update

diff --git a/Personal/bin/dmenu/cursors b/Personal/bin/dmenu/cursors
--- a/Personal/bin/dmenu/cursors
+++ b/Personal/bin/dmenu/cursors
@@ -34,7 +34,7 @@ case "${cursor_choice}" in
 		"Simp1e-Tokyo-Night-Light" "Simp1e-Tokyo-Night-Storm")
 	;;
 *)
-	printf 'Invalid choice.\n' >&2
+	printf 'Invalid choice.\nProgram terminated.\n' >&2
 	exit 1
 	;;
 esac
@@ -50,6 +50,6 @@ elif [[ -n ${theme_choice} ]]; then
 	sudo find /usr/share/icons/default/ -name "index.theme" -exec sed -i "/Inherits=/s/.*/Inherits=${theme_choice}/" {} \;
 	sudo sed -i "/cursor-theme-name=/s/.*/cursor-theme-name=${theme_choice}/" /etc/lightdm/slick-greeter.conf
 else
-	printf 'Invalid choice.\n' >&2
+	printf 'Invalid choice.\nProgram terminated.\n' >&2
 	exit 1
 fi
diff --git a/Personal/bin/dmenu/sh-prmpt-themer b/Personal/bin/dmenu/sh-prmpt-themer
--- a/Personal/bin/dmenu/sh-prmpt-themer
+++ b/Personal/bin/dmenu/sh-prmpt-themer
@@ -11,7 +11,7 @@ function set_oh_my_posh() {
 	declare -a options=("↵ Go Back" "Default" "di4am0nd" "illusi0n" "marcduiker" "robbyrussell")
 	THEME_CHOICE=$(printf '%s\n' "${options[@]}" | dmenu -i -l 6 -p 'Oh My Posh Themes:')
 	if [[ -z ${THEME_CHOICE} ]]; then
-		printf 'Invalid choice.\n' >&2
+		printf 'Invalid choice.\Program terminated.\n' >&2
 		exit 1
 	else
 		sed -i 's/^#eval "$(oh-my-posh init bash/eval "$(oh-my-posh init bash/' "${BASHRC}"
@@ -97,7 +97,7 @@ case ${CHOICE} in
 	;;
 *)
 	# Invalid choice
-	printf 'Invalid choice.\n' >&2
+	printf 'Invalid choice.\Program terminated.\n' >&2
 	exit 1
 	;;
 esac
